In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

What's the version of NumPy that you installed?

In [3]:
np.__version__

'1.20.1'

What's the version of NumPy that you installed?

In [4]:
pd.__version__

'1.2.4'

In [5]:
df=pd.read_csv('car_data.csv')

In [7]:
df.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

In [9]:
df.shape

(11914, 16)

What's the average price of BMW cars in the dataset?

In [12]:
df.groupby('Make').MSRP.mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [14]:
df1=df[df['Year'] >= 2015]

In [19]:
df1['Engine HP'].isnull().sum()

51

Calculate the average "Engine HP" in the dataset.

In [24]:
m1=df1['Engine HP'].mean()
m1

272.98771870794076

In [28]:
mean_hp_before=m1
print(round(mean_hp_before))

273


Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [25]:
df1['Engine HP'].fillna(m1)

32       160.0
33       160.0
34       160.0
41       240.0
42       240.0
         ...  
11898    300.0
11899    335.0
11900    300.0
11901    240.0
11902    335.0
Name: Engine HP, Length: 5995, dtype: float64

Now, calcualte the average of "Engine HP" again.

In [27]:
m2=df1['Engine HP'].fillna(m1).mean()
m2

272.98771870794116

In [29]:
mean_hp_after=m2
print(round(mean_hp_after))

273


Select all the "Rolls-Royce" cars from the dataset.

In [32]:
df2=df[df['Make']== 'Rolls-Royce']
df2.head(10)

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   
5278  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   
5279  Rolls-Royce            Ghost  2012  premium unleaded (required)   
5280  Rolls-Royce            Ghost  2012  premium unleaded (required)   
5281  Rolls-Royce            Ghost  2013  premium unleaded (required)   
5282  Rolls-Royce            Ghost  2013  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   
5278      563.0              12.0         AUTOMATIC  rear wheel drive   
5279      563.0              12.0         AUTOMATIC  rear wheel drive   
5280      563.0              12.0         AUTOMATIC  rear wheel drive   
5281      563.0              12.0         AUTOMATIC  rear wheel drive   
5282      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   
5278              4.0       Exotic,Luxury,Performance        Large   
5279              4.0       Exotic,Luxury,Performance        Large   
5280              4.0       Exotic,Luxury,Performance        Large   
5281              4.0       Exotic,Luxury,Performance        Large   
5282              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850  
5278         Sedan           21        13          86  329325  
5279         Sedan           20        13          86  250000  
5280         Sedan           20        13          86  290000  
5281         Sedan           21        13          86  296000  
5282         Sedan           21        13          86  256650

Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method

In [48]:
df2=df2[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
df2

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [58]:
x = df2.to_numpy()

In [59]:
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

Compute matrix-matrix multiplication between the transpose of X and X

In [67]:
xT=np.transpose(x)
xT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [89]:
#XTX=np.matmul(x,xT)
XTX=xT@x
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

Invert XTX

In [107]:
inv=np.linalg.inv(XTX)
inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

What's the sum of all the elements of the result?

In [108]:
total = np.sum(inv)

In [109]:
total

0.032212320677486195

Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]

In [110]:
y=np.array([1000,1100,900, 1200, 1000,850,1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [111]:
w1=(inv@xT)
w1

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [112]:
w=w1@y
w

array([ 0.19989598, 31.02612262, 31.65378877])